CREATE TABLE USERS (
    ID INT NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL
);

INSERT INTO USERS (ID, USER_NAME, PASSWORD) VALUES 
    (111, '111', '111'),
    (999, 'qwer', '0987'),
    (123, 'zxc', 'asd');

ALTER TABLE USERS ADD PRIMARY KEY (ID);
ALTER TABLE USERS MODIFY ID INT NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=100;
COMMIT;