FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
        && pecl install redis \
        && docker-php-ext-enable redis \
        && docker-php-ext-install mysqli \
        && docker-php-ext-enable mysqli

RUN curl -L https://github.com/bcit-ci/CodeIgniter/archive/refs/tags/3.1.11.tar.gz | tar xz --strip-components=1

RUN curl -L https://github.com/twbs/bootstrap/releases/download/v5.1.0/bootstrap-5.1.0-dist.zip -o bootstrap.zip && \
    unzip bootstrap.zip -d ./application/third_party/ && \
    rm bootstrap.zip
    
RUN curl -L https://code.jquery.com/jquery-3.6.0.min.js -o ./application/third_party/jquery.min.js

WORKDIR /var/www/html


ENTRYPOINT ["php-fpm"]
                                            
